### ISSUE TITLE
Impossible to edit customer if no calendars are linked

### ISSUE THREAD

**Issue by pamontag** [liguori/engagement-organizer#29]
Issue:
After creating a brand new customer is impossible to modify it, if you don't link it to a calendar event

Step to reproduce:
1. create a new customer
2. the customer is not showed in the customers page

**Comment by liguori** [comment]
Please, make sure you uncheck the "With appointments" checkbox in order to show all the customers, even the one not linked to an event on the calendar.
![image](https://user-images.githubusercontent.com/8238828/105614584-9f296800-5dca-11eb-9ba6-a090f488fb43.png)

If the check is not available for you, please upgrade to the new version :)
